import type { Metadata } from "next";
import Link from "next/link";
import "./styles.css";
import Footer from "./components/Footer";  


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="page-container">
          <div className="content-wrap">
            <nav className="top-nav">
              <div className="nav-text-large">
                  <Link href="/">My App</Link>
                </div>
              <ul className="nav-list">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>
                  <Link href="/posts">Posts</Link>            
                </li>
                <li>
                  <Link href="/contact">Contact</Link>            
                </li>
              </ul>
            </nav>
            <div className="container">
              {children}
            </div>
              <br/>
              <br/>
              <Footer />
            </div>
        </div>
      </body>
    </html>
  );
}
